openapi: "3.1.0"
info:
  title: "stock API"
  description: "stock API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /products:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Product"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
    put:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductUpdateDto"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Product malformed"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDto"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Product malformed"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
  /products/{id}:
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Id is not valid"
                Example#2:
                  value: "Missing id"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
    delete:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Id is not valid"
                Example#2:
                  value: "Missing id"
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                type: "object"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
  /product-category:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ProductCategory"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCategoryDto"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Malformed category"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductCategory"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
    /product-category/{id}:
      get:
        description: ""
        parameters:
          - name: "id"
            in: "path"
            required: true
            schema:
              type: "integer"
        responses:
          "400":
            description: "Bad Request"
            content:
              '*/*':
                schema:
                  type: "string"
                examples:
                  Example#1:
                    value: "Invalid id"
          "200":
            description: "OK"
            content:
              '*/*':
                schema:
                  $ref: "#/components/schemas/ProductCategory"
          "500":
            description: "Internal Server Error"
            content:
              '*/*':
                schema:
                  type: "object"
          "404":
            description: "Not Found"
            content:
              '*/*':
                schema:
                  type: "object"
components:
  schemas:
    ProductCategory:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        description:
          type: "string"
      required:
        - "id"
        - "name"
        - "description"
    Product:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        sku:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        price:
          type: "integer"
          format: "int32"
        cost:
          type: "integer"
          format: "int32"
        createdAt:
          type: "string"
          format: "date-time"
        category:
          $ref: "#/components/schemas/ProductCategory"
      required:
        - "id"
        - "sku"
        - "name"
        - "description"
        - "price"
        - "cost"
        - "createdAt"
        - "category"
    ProductUpdateDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        sku:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        price:
          type: "integer"
          format: "int32"
        cost:
          type: "integer"
          format: "int32"
        categoryId:
          type: "integer"
          format: "int32"
      required:
        - "id"
        - "sku"
        - "name"
        - "description"
        - "price"
        - "cost"
        - "categoryId"
    ProductDto:
      type: "object"
      properties:
        sku:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        price:
          type: "integer"
          format: "int32"
        cost:
          type: "integer"
          format: "int32"
        categoryId:
          type: "integer"
          format: "int32"
      required:
        - "sku"
        - "name"
        - "description"
        - "price"
        - "cost"
        - "categoryId"
    ProductCategoryDto:
      type: "object"
      properties:
        name:
          type: "string"
        description:
          type: "string"
      required:
        - "name"
        - "description"