ktor:
    application:
        modules:
            - com.integracion.ApplicationKt.module
    deployment:
        port: $PORT
postgres:
  url: $POSTGRES_URL
  user: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
h2:
  use-h2: $USE_IN_MEMORY_DB